AspNetCoreProject -Online Shopping/AspNetCoreProject/Controllers/CustomersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using AspNetCoreProject.Models;
using Microsoft.AspNetCore.Http;
using System.Text;

namespace AspNetCoreProject.Controllers
{
    public class CustomersController : Controller
    {
        private readonly ApplicationDbContext _context;

        public CustomersController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Customers
        public async Task<IActionResult> Index()
        {
            return View(await _context.Customers.ToListAsync());
        }
        [ServiceFilter(typeof(CommonActionFilter))]
        public IActionResult IndexSingle(int? CustomerId, int? ShippingId)
        {
            var singleSelectList = new SelectedInfoModel();

            singleSelectList.Customers = _context.Customers.ToList();

            if (CustomerId == null)
            {

                byte[] kkk = HttpContext.Session.Get("CustomerId");
                if (kkk != null)
                {
                    string someString = Encoding.ASCII.GetString(kkk);
                    CustomerId = Convert.ToInt32(someString);
                }
            }
            if (CustomerId != null)
            {
                HttpContext.Session.SetString("CustomerId", CustomerId.ToString());
                //geustFoodOrder.OrderFoods = _context.OrderFood.Where(w => w.GuestId == GuestId.Value).ToList();

                //Session["CustomerId"] = CustomerId;
                singleSelectList.Orders = _context.Orders.Where(w => w.CustomerId == CustomerId.Value).ToList();


            }

            if (ShippingId != null)
            {

                singleSelectList.ShippingInfos = _context.ShippingInfoes.Include(i => i.DeliveryBoy).Where(w => w.ShippingId == ShippingId.Value).ToList();

            }





            return View(singleSelectList);
        }



        // GET: Customers/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var customer = await _context.Customers
                .FirstOrDefaultAsync(m => m.CustomerId == id);
            if (customer == null)
            {
                return NotFound();
            }

            return View(customer);
        }

        // GET: Customers/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Customers/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("CustomerId,CustomerName,Address,Number")] Customer customer)
        {
            if (ModelState.IsValid)
            {
                _context.Add(customer);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(customer);
        }

        // GET: Customers/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var customer = await _context.Customers.FindAsync(id);
            if (customer == null)
            {
                return NotFound();
            }
            return View(customer);
        }

        // POST: Customers/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("CustomerId,CustomerName,Address,Number")] Customer customer)
        {
            if (id != customer.CustomerId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(customer);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CustomerExists(customer.CustomerId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(customer);
        }

        // GET: Customers/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var customer = await _context.Customers
                .FirstOrDefaultAsync(m => m.CustomerId == id);
            if (customer == null)
            {
                return NotFound();
            }

            return View(customer);
        }

        // POST: Customers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var customer = await _context.Customers.FindAsync(id);
            _context.Customers.Remove(customer);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CustomerExists(int id)
        {
            return _context.Customers.Any(e => e.CustomerId == id);
        }
    }
}

AspNetCoreProject -Online Shopping/AspNetCoreProject/Controllers/OrdersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using AspNetCoreProject.Models;

namespace AspNetCoreProject.Controllers
{
    public class OrdersController : Controller
    {
        private readonly ApplicationDbContext _context;

        public OrdersController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Orders
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.Orders.Include(o => o.Customer).Include(o => o.ShippingInfo);
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: Orders/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var order = await _context.Orders
                .Include(o => o.Customer)
                .Include(o => o.ShippingInfo)
                .FirstOrDefaultAsync(m => m.OrderId == id);
            if (order == null)
            {
                return NotFound();
            }

            return View(order);
        }

        // GET: Orders/Create
        public IActionResult Create()
        {
            ViewData["CustomerId"] = new SelectList(_context.Customers, "CustomerId", "Address");
            ViewData["ShippingId"] = new SelectList(_context.ShippingInfoes, "ShippingId", "ShippingCost");
            return View();
        }

        // POST: Orders/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("OrderId,Orderdate,CustomerId,ShippingId")] Order order)
        {
            if (ModelState.IsValid)
            {
                _context.Add(order);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["CustomerId"] = new SelectList(_context.Customers, "CustomerId", "Address", order.CustomerId);
            ViewData["ShippingId"] = new SelectList(_context.ShippingInfoes, "ShippingId", "ShippingCost", order.ShippingId);
            return View(order);
        }

        // GET: Orders/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var order = await _context.Orders.FindAsync(id);
            if (order == null)
            {
                return NotFound();
            }
            ViewData["CustomerId"] = new SelectList(_context.Customers, "CustomerId", "Address", order.CustomerId);
            ViewData["ShippingId"] = new SelectList(_context.ShippingInfoes, "ShippingId", "ShippingCost", order.ShippingId);
            return View(order);
        }

        // POST: Orders/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("OrderId,Orderdate,CustomerId,ShippingId")] Order order)
        {
            if (id != order.OrderId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(order);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!OrderExists(order.OrderId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["CustomerId"] = new SelectList(_context.Customers, "CustomerId", "Address", order.CustomerId);
            ViewData["ShippingId"] = new SelectList(_context.ShippingInfoes, "ShippingId", "ShippingCost", order.ShippingId);
            return View(order);
        }

        // GET: Orders/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var order = await _context.Orders
                .Include(o => o.Customer)
                .Include(o => o.ShippingInfo)
                .FirstOrDefaultAsync(m => m.OrderId == id);
            if (order == null)
            {
                return NotFound();
            }

            return View(order);
        }

        // POST: Orders/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var order = await _context.Orders.FindAsync(id);
            _context.Orders.Remove(order);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool OrderExists(int id)
        {
            return _context.Orders.Any(e => e.OrderId == id);
        }
    }
}

AspNetCoreProject -Online Shopping/AspNetCoreProject/Controllers/ProductsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using AspNetCoreProject.Models;

namespace AspNetCoreProject.Controllers
{
    public class ProductsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public ProductsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Products
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.Products.Include(p => p.Category);
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: Products/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var product = await _context.Products
                .Include(p => p.Category)
                .FirstOrDefaultAsync(m => m.ProductId == id);
            if (product == null)
            {
                return NotFound();
            }

            return View(product);
        }

        // GET: Products/Create
        public IActionResult Create()
        {
            ViewData["CategoryId"] = new SelectList(_context.Categories, "CategoryId", "CategoryName");
            return View();
        }

        // POST: Products/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ProductId,ProductName,CategoryId,price,ImageFile")] Product product)
        {
            if (ModelState.IsValid)
            {
                _context.Add(product);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["CategoryId"] = new SelectList(_context.Categories, "CategoryId", "CategoryName", product.CategoryId);
            return View(product);
        }

        // GET: Products/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var product = await _context.Products.FindAsync(id);
            if (product == null)
            {
                return NotFound();
            }
            ViewData["CategoryId"] = new SelectList(_context.Categories, "CategoryId", "CategoryName", product.CategoryId);
            return View(product);
        }

        // POST: Products/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ProductId,ProductName,CategoryId,price,ImageFile")] Product product)
        {
            if (id != product.ProductId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(product);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ProductExists(product.ProductId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["CategoryId"] = new SelectList(_context.Categories, "CategoryId", "CategoryName", product.CategoryId);
            return View(product);
        }

        // GET: Products/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var product = await _context.Products
                .Include(p => p.Category)
                .FirstOrDefaultAsync(m => m.ProductId == id);
            if (product == null)
            {
                return NotFound();
            }

            return View(product);
        }

        // POST: Products/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var product = await _context.Products.FindAsync(id);
            _context.Products.Remove(product);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ProductExists(int id)
        {
            return _context.Products.Any(e => e.ProductId == id);
        }
    }
}

AspNetCoreProject -Online Shopping/AspNetCoreProject/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>NIBIR FASHION</title>
    <link rel="icon" type="image/x-icon" href="~/images/nibir fashion.png">

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body style="background-color:#f5ddf3">
    <nav class="navbar navbar-inverse navbar-fixed-top" style="background-color:#a70593"  >

        @*<a href="@Url.Action("Index", "Home")" class="navbar-brand">
            <img src="~/images/nibir fashion.png" title="NIBIR FASHION" alt="" height="40" width="40" class="rounded-circle"/>
        </a>*@
        <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">NiBIR FASHION</a>
        <div class="container">


            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>

               
            </div>
            <div class="navbar-collapse collapse">

               

                
                @if (Context.User.Identity.IsAuthenticated)
                {
                    <ul class="nav navbar-nav navbar-left">
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Detalse  <span class="caret"></span>
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                                <ul>
                                    <li><a asp-area="" asp-controller="Categories" asp-action="Index">Categories</a></li>
                                    <li><a asp-area="" asp-controller="CustomerReviews" asp-action="Index">CustomerReviews</a></li>
                                    <li><a asp-area="" asp-controller="Customers" asp-action="Index">Customers</a></li>
                                    <li><a asp-area="" asp-controller="DeliveryBoys" asp-action="Index">DeliveryBoys</a></li>
                                    <li class="divider"></li>
                                    <li><a asp-area="" asp-controller="Employees" asp-action="Index">Employees</a></li>
                                    <li><a asp-area="" asp-controller="OrderDtls" asp-action="Index">OrderDtls</a></li>
                                    <li><a asp-area="" asp-controller="Orders" asp-action="Index">Orders</a></li>
                                    <li class="divider"></li>

                                    <li><a asp-area="" asp-controller="Products" asp-action="Index">Products</a></li>
                                    <li><a asp-area="" asp-controller="ShippingInfoes" asp-action="Index">ShippingInfoes</a></li>


                                </ul>
                            </div>
                        </li>
                    </ul>

                    <ul class="nav navbar-nav navbar-right">

                        <li><a asp-area="" asp-controller="Customers" asp-action="IndexSingle">Multipal Select</a></li>
                        <li><a asp-area="" asp-controller="DeliveryBoys" asp-action="Sample">Multipal Insert</a></li>
                        <li><a asp-area="" asp-controller="Employees" asp-action="Index">Employees</a></li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Admin Panal <span class="caret"></span>
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                                <ul>
                                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                                    <li><a asp-area="" asp-controller="Home" asp-action="About">About</a></li>
                                    <li><a asp-area="" asp-controller="Home" asp-action="Contact">Contact</a></li>
                                    <li><a asp-area="" asp-controller="Account" asp-action="Login">LogIn</a></li>
                                    <li class="divider"></li>
                                    <li><a asp-area="" asp-controller="Account" asp-action="Register">Register</a></li>
                                    <li><a asp-area="" asp-controller="Account" asp-action="Roll">Roll</a></li>
                                    <li><a asp-area="" asp-controller="Account" asp-action="RollMappingToUserList">RoleMapToUser</a></li>
                                    <li class="divider"></li>

                                    <li><a asp-area="" asp-controller="MenuHelperModels" asp-action="Index">MenuSettup</a></li>
                                    <li><a asp-area="" asp-controller="MenuModels" asp-action="Index">MenuWithRoll</a></li>

                                    <li><a asp-area="" asp-controller="MenuModelManages" asp-action="Index">MenuPermission</a></li>
                                    <li class="divider"></li>
                                    <li><a asp-area="" asp-controller="Account" asp-action="Logout">Logout</a></li>


                                </ul>

                            </div>
                        </li>

                        <li><a asp-area="" asp-controller="Account" asp-action="Login">@User.Identity.Name</a></li>
                        <li><a asp-area="" asp-controller="Account" asp-action="Logout">Logout</a></li>
                    </ul>
                }
                else
                {
            <ul class="nav navbar-nav navbar-right">
                <li><a asp-area="" asp-controller="Account" asp-action="Login">Login</a></li>
                <li><a asp-area="" asp-controller="Account" asp-action="Register">Register</a></li>
            </ul>
                }
                <ul class="nav navbar-nav navbar-right">



                    @*<li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Admin Panal <span class="caret"></span>
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                    <ul>
                        <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                        <li><a asp-area="" asp-controller="Home" asp-action="About">About</a></li>
                        <li><a asp-area="" asp-controller="Home" asp-action="Contact">Contact</a></li>
                        <li><a asp-area="" asp-controller="Account" asp-action="Login">LogIn</a></li>
                        <li class="divider"></li>
                        <li><a asp-area="" asp-controller="Account" asp-action="Register">Register</a></li>
                        <li><a asp-area="" asp-controller="Account" asp-action="Roll">Roll</a></li>
                        <li><a asp-area="" asp-controller="Account" asp-action="RollMappingToUserList">RoleMapToUser</a></li>
                        <li class="divider"></li>

                        <li><a asp-area="" asp-controller="MenuHelperModels" asp-action="Index">MenuSettup</a></li>
                        <li><a asp-area="" asp-controller="MenuModels" asp-action="Index">MenuWithRoll</a></li>

                        <li><a asp-area="" asp-controller="MenuModelManages" asp-action="Index">MenuPermission</a></li>
                        <li class="divider"></li>
                        <li><a asp-area="" asp-controller="Account" asp-action="Logout">Logout</a></li>


                    </ul>

                </div>
            </li>*@


                </ul>
                @*<ul class="nav navbar-nav navbar-right">
            <li><a asp-area="" asp-controller="Customers" asp-action="IndexSingle">Multipal Select</a></li>
            <li><a asp-area="" asp-controller="DeliveryBoys" asp-action="Sample">Multipal Insert</a></li>
            <li><a asp-area="" asp-controller="Employees" asp-action="Index">Employees</a></li>
        </ul>*@
                <ul class="nav navbar-nav navbar-left">
                    @*<li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Detalse  <span class="caret"></span>
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                    <ul>
                        <li><a asp-area="" asp-controller="Categories" asp-action="Index">Categories</a></li>
                        <li><a asp-area="" asp-controller="CustomerReviews" asp-action="Index">CustomerReviews</a></li>
                        <li><a asp-area="" asp-controller="Customers" asp-action="Index">Customers</a></li>
                        <li><a asp-area="" asp-controller="DeliveryBoys" asp-action="Index">DeliveryBoys</a></li>
                        <li class="divider"></li>
                        <li><a asp-area="" asp-controller="Employees" asp-action="Index">Employees</a></li>
                        <li><a asp-area="" asp-controller="OrderDtls" asp-action="Index">OrderDtls</a></li>
                        <li><a asp-area="" asp-controller="Orders" asp-action="Index">Orders</a></li>
                        <li class="divider"></li>

                        <li><a asp-area="" asp-controller="Products" asp-action="Index">Products</a></li>
                        <li><a asp-area="" asp-controller="ShippingInfoes" asp-action="Index">ShippingInfoes</a></li>


                    </ul>
                </div>
            </li>*@
                    <li><a asp-area="" asp-controller="Home" asp-action="About">About</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Contact">Contact</a></li>
                </ul>

            </div>
        </div>
    </nav>

    <partial name="_CookieConsentPartial" />

    <div class="container body-content" style="background-color:#f6bef1">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.ToString()-all right reserved by NIBIR FASHION </p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-aJ21OjlMXNL5UyIl/XNwTMqvzeRMZH2w8c5cRVpzpU8Y5bApTppSuUkhZXN0VxHd">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>