AspNetCoreProject -Online Shopping/AspNetCoreProject/Controllers/CustomerReviewsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using AspNetCoreProject.Models;
using Microsoft.AspNetCore.Hosting;
using System.IO;
using Microsoft.AspNetCore.Http;

namespace AspNetCoreProject.Controllers
{
    public class CustomerReviewsController : Controller
    {
        private readonly ApplicationDbContext _context;

        private readonly IHostingEnvironment _env;

        public CustomerReviewsController(ApplicationDbContext context , IHostingEnvironment env)
        {
            _context = context;
            _env = env;
        }

        // GET: CustomerReviews
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.CustomerReviews.Include(c => c.Customer);
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: CustomerReviews/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var customerReview = await _context.CustomerReviews
                .Include(c => c.Customer)
                .FirstOrDefaultAsync(m => m.ReviewId == id);
            if (customerReview == null)
            {
                return NotFound();
            }

            return View(customerReview);
        }

        // GET: CustomerReviews/Create
        public IActionResult Create()
        {
            ViewData["CustomerId"] = new SelectList(_context.Customers, "CustomerId", "Address");
            return View();
        }

        // POST: CustomerReviews/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ReviewId,CustomerId,Opinion,ImageFile")] CustomerReview customerReview ,IFormFile formFile)
        {
            if (ModelState.IsValid)
            {
                string imagePath = _env.WebRootPath + "\\Images\\" + formFile.FileName;
                using (var stream = new FileStream(imagePath, FileMode.Create))
                {
                    formFile.CopyTo(stream);
                }

                customerReview.ImageFile = "~/Images/" + formFile.FileName;
                _context.Add(customerReview);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["CustomerId"] = new SelectList(_context.Customers, "CustomerId", "Address", customerReview.CustomerId);
            return View(customerReview);
        }

        // GET: CustomerReviews/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            
            var customerReview = await _context.CustomerReviews.FindAsync(id);
            if (customerReview == null)
            {
                return NotFound();
            }
            ViewData["CustomerId"] = new SelectList(_context.Customers, "CustomerId", "Address", customerReview.CustomerId);
            return View(customerReview);
        }

        // POST: CustomerReviews/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ReviewId,CustomerId,Opinion,ImageFile")] CustomerReview customerReview, IFormFile formFile)
        {
            if (id != customerReview.ReviewId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    if (formFile != null)
                    {

                        string imagePath = _env.WebRootPath + "\\Images\\" + formFile.FileName;
                        using (var stream = new FileStream(imagePath, FileMode.Create))
                        {
                            formFile.CopyTo(stream);
                        }

                        customerReview.ImageFile = "~/Images/" + formFile.FileName;


                    }


                    _context.Update(customerReview);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CustomerReviewExists(customerReview.ReviewId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["CustomerId"] = new SelectList(_context.Customers, "CustomerId", "Address", customerReview.CustomerId);
            return View(customerReview);
        }

        // GET: CustomerReviews/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var customerReview = await _context.CustomerReviews
                .Include(c => c.Customer)
                .FirstOrDefaultAsync(m => m.ReviewId == id);
            if (customerReview == null)
            {
                return NotFound();
            }

            return View(customerReview);
        }

        // POST: CustomerReviews/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var customerReview = await _context.CustomerReviews.FindAsync(id);
            _context.CustomerReviews.Remove(customerReview);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CustomerReviewExists(int id)
        {
            return _context.CustomerReviews.Any(e => e.ReviewId == id);
        }
    }
}

AspNetCoreProject -Online Shopping/AspNetCoreProject/Views/CustomerReviews/Create.cshtml
@model AspNetCoreProject.Models.CustomerReview

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create</h2>

<h4>CustomerReview</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create" asp-controller="CustomerReviews" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="CustomerId" class="control-label"></label>
                <select asp-for="CustomerId" class ="form-control" asp-items="ViewBag.CustomerId"></select>
            </div>
            <div class="form-group">
                <label asp-for="Opinion" class="control-label"></label>
                <input asp-for="Opinion" class="form-control" />
                <span asp-validation-for="Opinion" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ImageFile" class="control-label"></label>
                <input class="form-control" name="formFile" type="file" />
                @*<input asp-for="ImageFile" class="form-control" />*@
                
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

AspNetCoreProject -Online Shopping/AspNetCoreProject/Views/CustomerReviews/Delete.cshtml
@model AspNetCoreProject.Models.CustomerReview

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>CustomerReview</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Opinion)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Opinion)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.ImageFile)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ImageFile)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Customer)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Customer.Address)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="ReviewId" />
        <input type="submit" value="Delete" class="btn btn-default" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

AspNetCoreProject -Online Shopping/AspNetCoreProject/Views/CustomerReviews/Details.cshtml
@model AspNetCoreProject.Models.CustomerReview

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>CustomerReview</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Opinion)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Opinion)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.ImageFile)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ImageFile)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Customer)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Customer.Address)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.ReviewId">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

AspNetCoreProject -Online Shopping/AspNetCoreProject/Views/CustomerReviews/Edit.cshtml
@model AspNetCoreProject.Models.CustomerReview

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>

<h4>CustomerReview</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit" asp-controller="CustomerReviews" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="ReviewId" />
            <div class="form-group">
                <label asp-for="CustomerId" class="control-label"></label>
                <select asp-for="CustomerId" class="form-control" asp-items="ViewBag.CustomerId"></select>
                <span asp-validation-for="CustomerId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Opinion" class="control-label"></label>
                <input asp-for="Opinion" class="form-control" />
                <span asp-validation-for="Opinion" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ImageFile" class="control-label"></label>
                <input  class="form-control" name="formFile" type="file" />
                
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

AspNetCoreProject -Online Shopping/AspNetCoreProject/Views/CustomerReviews/Index.cshtml
@model IEnumerable<AspNetCoreProject.Models.CustomerReview>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Index</h2>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Opinion)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ImageFile)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Customer)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Opinion)
            </td>
            <td>
                <img src="@Url.Content(item.ImageFile)" alt="Card Image" height="100" width="100" />
                @*@Html.DisplayFor(modelItem => item.ImageFile)*@
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Customer.Address)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.ReviewId">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.ReviewId">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.ReviewId">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>